// Common dropdown options used across the application

export const BRANCHES = [
  'Computer Science Engineering (CSE)',
  'Information Technology (IT)',
  'Electronics and Communication Engineering (ECE)',
  'Electrical Engineering (EE)',
  'Mechanical Engineering (ME)',
  'Civil Engineering (CE)',
  'Biotechnology (BT)',
  'Engineering Physics (EP)',
  'Mathematics and Computing (MnC)',
  'Electronics and Instrumentation Engineering (EIE)'
];

export const JOB_ROLES = [
  'Software Engineer',
  'Frontend Developer',
  'Backend Developer',
  'Full Stack Developer',
  'Data Scientist',
  'Data Analyst',
  'Machine Learning Engineer',
  'DevOps Engineer',
  'Cloud Engineer',
  'Mobile App Developer',
  'UI/UX Designer',
  'Product Manager',
  'Business Analyst',
  'Quality Assurance Engineer',
  'Network Engineer',
  'System Administrator',
  'Cybersecurity Analyst',
  'Hardware Engineer',
  'Embedded Systems Engineer',
  'Research & Development',
  'Technical Consultant',
  'Project Manager',
  'Other'
];

export const SKILLS = [
  'JavaScript',
  'Python',
  'Java',
  'C++',
  'C',
  'React',
  'Angular',
  'Vue.js',
  'Node.js',
  'Express.js',
  'Django',
  'Flask',
  'Spring Boot',
  'MongoDB',
  'MySQL',
  'PostgreSQL',
  'HTML',
  'CSS',
  'Tailwind CSS',
  'Bootstrap',
  'Git',
  'Docker',
  'Kubernetes',
  'AWS',
  'Azure',
  'Google Cloud',
  'Machine Learning',
  'Deep Learning',
  'TensorFlow',
  'PyTorch',
  'Data Structures',
  'Algorithms',
  'SQL',
  'NoSQL',
  'REST APIs',
  'GraphQL',
  'TypeScript',
  'Redux',
  'Next.js',
  'Flutter',
  'React Native',
  'Android Development',
  'iOS Development',
  'UI/UX Design',
  'Figma',
  'Adobe XD',
  'Photoshop',
  'Data Analysis',
  'Excel',
  'Power BI',
  'Tableau',
  'R Programming',
  'MATLAB',
  'Embedded Systems',
  'Arduino',
  'Raspberry Pi',
  'IoT',
  'Blockchain',
  'Cybersecurity',
  'Networking',
  'Linux',
  'Agile',
  'Scrum'
];
